name: .NET build and test

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  buildAndTest:
    name: Building and testing on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install dependencies
      working-directory: FSHF Standard library
      run: dotnet restore

    - name: Build
      working-directory: FSHF Standard library
      run: dotnet build --configuration Release --no-restore
  
    - name: Unit tests
      working-directory: FSHF Standard library
      run: >
        dotnet test
        --filter Category=Unit
        --configuration Release --no-restore
        --verbosity normal --collect:"XPlat Code Coverage"
        --results-directory:"UnitTestResults"
        -- RunConfiguration.DisableAppDomain=true

    - name: Integration tests with Internet data access tests
      working-directory: FSHF Standard library
      run: >
        dotnet test --filter Category=IntegrationWithInternetDataAccess 
        --configuration Release --no-restore 
        --verbosity normal --collect:"XPlat Code Coverage" 
        --results-directory:"IntegrationWithInternetDataAccessTestResults"  
        -- RunConfiguration.DisableAppDomain=true

    - name: Codecov for integration tests with Internet data access
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v1.3.2
      with:
        file: IntegrationWithInternetDataAccessTestResults/**/*.xml
        env_vars: ubuntu-latest
        name: Code Coverage for integration tests with Internet data access on ubuntu-latest
        flags: IntegrationTestsWithInternetDataAccess
        verbose: false

    - name: Publish Codecov results for unit tests
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v1.3.2
      with:
        file: UnitTestResults/**/*.xml
        env_vars: ${{ matrix.os }}
        name: Code Coverage for unit tests on ${{ matrix.os }}
        flags: UnitTests
        verbose: false