name: .NET build and publish package

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      working-directory: FSHF Standard library
      run: dotnet restore
    - name: Build
      working-directory: FSHF Standard library
      run: dotnet build --configuration Release --no-restore
    - name: Create the package
      working-directory: FSHF Standard library
      run: dotnet pack --configuration Release
    - name: Publish FSHFStandardLibrary.Core to nuget. 
      working-directory: FSHF Standard library 
      run: dotnet nuget push FSHFStandardLibrary.Core/bin/Release/*.nupkg --api-key ${{secrets.NUGET}} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish FSHFStandardLibrary.Implementations to nuget. 
      working-directory: FSHF Standard library 
      run: dotnet nuget push FSHFStandardLibrary.Implementations/bin/Release/*.nupkg --api-key ${{secrets.NUGET}} --source https://api.nuget.org/v3/index.json --skip-duplicate
